using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaffyScript.Compiler.FrontEnd
{
    public enum TokenType
    {
        AndEquals,
        Argument,
        As,
        Assign,
        Base,
        BitwiseAnd,
        BitwiseOr,
        Bool,
        Break,
        Case,
        CloseBrace,
        CloseBracket,
        CloseParen,
        Colon,
        Comma,
        Complement,
        Continue,
        Decrement,
        Default,
        DivEquals,
        Divide,
        Do,
        Dot,
        Else,
        Enum,
        EoF,
        Equal,
        Event,
        For,
        GreaterThan,
        GreaterThanOrEqual,
        Identifier,
        If,
        Import,
        Increment,
        LessThan,
        LessThanOrEqual,
        LogicalAnd,
        LogicalOr,
        Minus,
        ModEquals,
        Modulo,
        MulEquals,
        Multiply,
        Namespace,
        New,
        Not,
        NotEqual,
        Number,
        Object,
        OpenBrace,
        OpenBracket,
        OpenParen,
        OrEquals,
        Plus,
        PlusEquals,
        QuestionMark,
        ReadOnly,
        Repeat,
        Return,
        Script,
        SemiColon,
        ShiftLeft,
        ShiftRight,
        String,
        SubEquals,
        Switch,
        Until,
        Using,
        Var,
        While,
        With,
        Xor,
        XorEquals
    }
}
